### ISSUE TITLE
Save game files

### ISSUE THREAD

**Issue by hogsy** [TalonBraveInfo/OpenHoW#10]
Are we going to support those from the original game? I think we should but thus far I haven't bothered to look at the format used in the game, seems to be 'savearmy*' in the PC version (with a number appended to it).

It would take a hell of a long time to do this without the original source I'd imagine.

**Comment by DummkopfOfHachtenduden** [comment]
Some information on the topic. https://www.dlh.net/en/cheats/22836/hogs-of-war.html

**Comment by hogsy** [comment]
We'll just go with our own thing in that case :)
