### ISSUE TITLE
Vertex normals are being incorrectly generated for vertical faces

### ISSUE THREAD

**Issue by DummkopfOfHachtenduden** [TalonBraveInfo/OpenHoW#107]
This might be an issue with normals / backfaces or geometry itself.

- Some objects like the grass is not lit at all.
![image](https://user-images.githubusercontent.com/13951844/63571150-ad44da80-c57f-11e9-8789-4f9054cde4d8.png)

- Trees are partially lit.
https://www.youtube.com/watch?v=LtbeeqO5Ywc

**Comment by hogsy** [comment]
Looks like a fault with the normals generation.

![image](https://user-images.githubusercontent.com/1946366/63589453-1e48ba00-c5a1-11e9-9780-9c1a2da0194e.png)

**Comment by hogsy** [comment]
Partially depends on https://github.com/TalonBraveInfo/OpenHoW/issues/124 as there are some cases which our automatic normals generation can't deal with unless we handle specific cases (e.g. generate face normals for boxes etc.)

**Comment by hogsy** [comment]
Amendments have been made which will alleviate this issue in some cases. Closing in favour of https://github.com/TalonBraveInfo/OpenHoW/issues/124
