### ISSUE TITLE
If you want to follow the path of FreeDOOM, don't repeat it's mistakes.

### ISSUE THREAD

**Issue by marespiaut** [TalonBraveInfo/OpenHoW#125]
Hello,

I have discovered your project, and, as an old HoW player, I can't wait to try your engine when the game will start to be playable.

I've read in your README that you want to produce free assets, and you cite FreeDOOM as an example.

I support your end goal, but also encourage you to take FreeDOOM as a counter-example…

While the intentions of FreeDOOM are commendable, the end result is, in my humble opinion, nothing but a catastrophe: The art style is inconsistent, confusing, and above all ugly.

If you intend to replace the original assets, the average player will expect, in the worst case, something as good as the original. In the best case, something better.

I strongly encourage you to take this huge task seriously, and hire a professional and motivated artist via a fundraising.

In the meantime, I wish you a happy development.

Best regards.

**Comment by hogsy** [comment]
Thanks for the heads up! Will certainly keep it in mind.

**Comment by hogsy** [comment]
When the project is further along I will open a donation pool for hiring a professional - will need to go through conceptualising first which will require some discussion. Still all a ways off.

Closing this ticket for now.
