### ISSUE TITLE
Flying airships

### ISSUE THREAD

**Issue by hogsy** [TalonBraveInfo/OpenHoW#145]
Brrrrrmmm

- [x] Airship class derived from vehicle class?
- [x] Ambient sound follows ship around
- [ ] Ship flies above max level height by some units?
- [x] Random path around map or is there actually a pattern?

**Comment by hogsy** [comment]
@DummkopfOfHachtenduden can you add your notes here? And I can then move it across for the v0.5.0 milestone.

**Comment by DummkopfOfHachtenduden** [comment]
Recorded camp path after 18 minutes:
![image](https://user-images.githubusercontent.com/13951844/75346470-1135bc00-589f-11ea-999d-4b031d7b421c.png)

- Paths way-points seem to be random.
- Waypoints are always inside play-area but turn radius may overshoot it.
- Airship is visually banking into turns
- Always turning left, just like my Roomba.
- Height is fixed while flying but varies between maps although not a fixed increment based on highest point in terrain. We could set it in map.manifest but there needs to be a function to reliably place skyline objects on generated maps as well (airship, butterflies, birds, etc.)
CAMP:  `TerrainMaxHeight=4352; AirshipHeight=5559` PLAY: `TerrainMaxHeight=5952; AirshipHeight=10448`.

**Comment by hogsy** [comment]
Thanks!
