### ISSUE TITLE
Updating Windows build

### ISSUE THREAD

**Issue by Ben2917** [TalonBraveInfo/OpenHoW#158]
Hello,

I've been following the project on and off for a little while and thought this could be a good way to start contributing. I've noticed in the read me that there is a mention of making building on Windows a bit more friendly at some point in the future. 

On my fork of the repo, I have everything building in Windows 10 using MSYS2 and MinGW, linking against the prebuilt MSYS2 packages for OpenAL, SDL2, etc.

If there's any interest in integrating these changes into the project just let me know as I'd be happy to clean up what I've got, update the read me, and submit a pull request.

Cheers

**Comment by hogsy** [comment]
Apologies for the slight delay. Sure, feel free to clean up what you have and submit a pull request, and I would be more than happy to review what you've done.

**Comment by hogsy** [comment]
@Ben2917 I'll go ahead and close this issue for now. Feel free to open a pull request whenever you're ready and I'll certainly check it out! 😄
