### ISSUE TITLE
Implement unmangle function to deal with frontend resources

### ISSUE THREAD

**Issue by hogsy** [TalonBraveInfo/OpenHoW#20]
The original PSX implementation can be found [here](https://gist.github.com/hogsy/7a24af4c3bd1c6b0c294351ffd9b1f2d) - keep in mind this is written using the MIPS instruction set, so it's going to need conversion.

Can probably just be added to `pork_utils.c` as `pork_unmangle`

**Comment by DummkopfOfHachtenduden** [comment]
The Sony Playstation 1 has a [RISC R3000A](https://en.wikipedia.org/wiki/R3000) processor which uses the [MIPS 1](https://en.wikipedia.org/wiki/MIPS_architecture) instruction set. 

It has a branch delay slot which means...
```
		beq	t0,zero,exit 			; Zero byte indicates end of data
		andi	t0,t0,$003f				; Mask bits 0 to 5
```
... `andi` is executed **before** and **regardless** of `beq` being taken or not.

**Comment by DummkopfOfHachtenduden** [comment]
[UNMANGLE.H](https://github.com/Xrampino/Actua-Soccer/blob/6375c0a35c20cffe699fd160543229b1b1581e57/UNMANGLE.H)
[UNMANGLE.C](https://github.com/Xrampino/Actua-Soccer/blob/6375c0a35c20cffe699fd160543229b1b1581e57/UNMANGLE.C)

**Comment by hogsy** [comment]
Fortunately this can sit low on our list of priorities as at this time supporting both the PSX and PC releases would be an absolute mess - and the PC version only appears to have the frontend resources mangled.
