### ISSUE TITLE
Implementation of sky

### ISSUE THREAD

**Issue by hogsy** [TalonBraveInfo/OpenHoW#27]
* Using `skydome` mesh
* Investigated possibility of using skybox instead for simplification - this isn't possible with current assets
* Introduced `pork_find2` while working on this to deal with loading textures from mod/base with potentially different extensions (e.g. search mod for `file.png`, `file.bmp` etc first, then do same for base if we don't find anything)
* Texture set for sky is defined in .description files e.g. `"sky": "sunny"` - so load in sunny1 to 4 - we're assuming this was hard-coded right now
* ~~Dome needs to be position at camera (shouldn't move with world)~~

----

- [x] If texture field is blank, use gradient sky, otherwise texture takes priority
- [x] Implementation of gradient sky + dome
- [x] Set clear colour to the bottom gradient colour on map load
- [ ] Use sprites for clouds orbiting around map oriented towards viewer (only if no texture is specified)
- [ ] Investigate volumetric clouds as a possible option (parallax?)
- [x] Investigate single-layer procedural cloud scroll produced in shader
- [x] What is _skydomeu_ for?

----

## PSX

This implementation uses a simple gradient to represent the sky that seems to be applied to the sky dome.

Clouds are then layered on top.

![image](https://user-images.githubusercontent.com/1946366/55149692-8a360c00-5142-11e9-825b-90e5485ced10.png)

**Comment by DummkopfOfHachtenduden** [comment]
The same clouds / stars used on PSX are included in the PC version as Skys folder. Are those implemented in the PC version? The images from `Chars/SUNNY` already contain clouds as they are panorama pictures.

`Chars/SPACE/earth4` is streched in texture but projected correctly on both sphere halves. Might be a hint?
![image](https://user-images.githubusercontent.com/13951844/40915635-1f057b48-67fd-11e8-9478-8b04ae74cb7a.png)

`skydomeu` is the bottom half of the skysphere, inverted for fake sky-reflections on water.

**Comment by hogsy** [comment]
https://trello.com/c/WkuFoq9X/9-implementation-of-sky-sphere

**Comment by hogsy** [comment]
Pushing back to next milestone.

**Comment by hogsy** [comment]
![image](https://user-images.githubusercontent.com/1946366/58750951-44722880-8490-11e9-9700-0cb69226a5b7.png)

**Comment by hogsy** [comment]
>  Investigate single-layer procedural cloud scroll produced in shader

Ditched.

This is also put back for now until sprites implementation is completed - will be used for clouds

**Comment by hogsy** [comment]
Few notes regarding the progress on this task.
* Clouds in the game are split up into multiple textures - they're possibly glued together randomly to add some variation? Need to investigate this further but no hurry
* Clouds depend on the sprite implementation which is in progress
* Maps should decide whether to use PSX/PC style sky instead of the user, otherwise custom maps will potentially need to support both - just makes things awkward otherwise (maybe if texture field is empty, just assume it's PSX style)

**Comment by hogsy** [comment]
I'm having second thoughts on even bothering to support textures for the sky, personally I prefer the look of the sky in the PSX version of the game. The textures used for the sky in the PC version are pretty low-resolution and they don't play well with the clouds (hence why the PC version didn't use them).

This would also simplify the implementation and we can probably just class this as completed minus the clouds (for which I'll move the points into a separate ticket).

Thoughts @DummkopfOfHachtenduden and @solemnwarning?

**Comment by hogsy** [comment]
Closing following conversation. Ticket for clouds has been raised [here](https://github.com/TalonBraveInfo/OpenHoW/issues/98).
