### ISSUE TITLE
Generate texture for minimap representation

### ISSUE THREAD

**Issue by hogsy** [TalonBraveInfo/OpenHoW#29]
This would follow the original implementation, which also generated a texture to represent the minimap displayed within the HUD.

I'll need to see if I can view the game in a wireframe state, as the plane used for the minimap doesn't actually appear to be totally flat?

## Questions

* Is the plane used to represent the minimap actually flat?
* How does it decide on the tile colours, is it simply finding the average?
* Is there any data provided within the map files that's specific towards how the minimap is displayed?

## Observations

* Minimap will rotate with the camera (don't appear to be any other factors at play here)
* It's slightly larger on the PSX version than on PC (very likely due to resolution)
* On PC it uses linear filtering on the minimap (absent on PSX due to technical limitations)
* Might be based on the implementation used in the Actua game series - see [here](https://www.youtube.com/watch?v=exq-pQC3ZpE)

## Suggestions

* Allow loading external minimap if it exists

**Comment by DummkopfOfHachtenduden** [comment]
A map has 64x64 tiles and even tho "Chars/TOP.MTD/" is obsolete the textures are 64x64.
With a direct mapping of a tile to a pixel we just need to figure some colors per type.

Here are my estimated colors (based on screenshot color values):    

TileType | Red | Green | Blue
-------- | --- | ----- | ----
Mud      | 132 | 107   | 82
Grass    | 99  | 182   | 99
Metal    | -   | -     | -
Wood     | -   | -     | -
Water    | 90  | 90    | 157
Stone    | 99  | 99    | 99
Rock     | 99  | 99    | 99
Sand     | 223 | 182   | 66
Ice      | 190 | 255   | 255
Snow     | 255 | 255   | 255
Quag     | -   | -     | -
Lava     | -   | -     | -
IsWatery | -   | -     | -
IsMine	 | 255 | 0     | 0
IsWall   | -   | -     | -

Metal, Wood & Quag does not offically exist in any map, maybe it's in the code tho but I'd need to modify some values to confirm that. 
Lava only exists as poison water, which does not match FT_LAVA.wav.

This is what I managed to do:
![image](https://user-images.githubusercontent.com/13951844/42323369-428f44ba-8060-11e8-93bc-b9b4bbd26947.png)

Original (PSX) for reference:
![image](https://user-images.githubusercontent.com/13951844/42323668-34851290-8061-11e8-8303-361b38984db8.png)

My base colors are mostly accurate except for one of the the sides of the small lake.
The shading probably needs a bit of work to get right, lower areas generally get darker.

**Comment by hogsy** [comment]
I've got details on the original shading algorithm used, just need to get round to implementing it.

**Comment by hogsy** [comment]
Initial implementation is completed, after some headaches. Will finish the rest soon.

![image](https://user-images.githubusercontent.com/1946366/46261273-37f49500-c4e9-11e8-9957-a4427336995e.png)

**Comment by hogsy** [comment]
Very close to finishing this now - just need to do some last tweaks to get the brightness matching up.
