### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by DummkopfOfHachtenduden** [TalonBraveInfo/OpenHoW#5]
These are for `CRLF` and `SPACE`, same struct.
https://github.com/TalonBraveInfo/OpenHoW/blob/1c448f6690263497b7bd31af2deef628deac84dc/libpork/font.c#L77-L78

These are X and Y offset (16 bit each) for the character. The TabBlock[2] (without seeking the 16 bytes) marking the origin. `tab.X - origin.X` and `tab.Y - origin.Y`  is then the topLeft of the character on the bitmap.
https://github.com/TalonBraveInfo/OpenHoW/blob/1c448f6690263497b7bd31af2deef628deac84dc/libpork/font.c#L83-L84

**Comment by hogsy** [comment]
done
