### ISSUE TITLE
Map configuration editor

### ISSUE THREAD

**Issue by hogsy** [TalonBraveInfo/OpenHoW#66]
Very simple editor provided that can modify and create map manifests - can be used to create all the other missing manifests.

- [x] Allow creation of a new manifest
- [x] Provide a list of existing manifests (can refer to cached list)
- [x] Allow us to modify an existing manifest
- [x] Straight forward interface, fields for each possible option we provide with drop down lists etc.
- [x] Skies as a simple text input field (just enter the name of the directory, e.g. 'sunny')
- [ ] Drop down to select weather only needs 'Snow, Rain and None' right now
- [ ] Move each DebugWindow child class into it's own header
- [x] Add save functionality
- [x] Remove Open prompt (we're using main open prompt now!)
- [ ] Selector for climate and TOD

----

Some new data that each manifest needs in relation to the weather.

- [x] Ambience colour
- [x] Sun direction/position
- [x] Sun colour
- [x] Climate (Hot/Cold)
- [x] Time of Day (Day/Night)

**Comment by hogsy** [comment]
Partially completed, though not in the standard I would have liked but gave me a good opportunity to overhaul a bunch of stuff which should be of benefit towards the game-mode implementation.

**Comment by DummkopfOfHachtenduden** [comment]
Maps have either DAY or NIGHT ambient sounds. sfxday.srl and sfxnight.srl are not reliable!
- `AMB_1D.wav` / `AMB_1N.wav`
- `AMB_2D.wav` / `AMB_2N.wav`

I'd also suggest adding HOT as weather to accommodate these animations + sounds properly unless you want to add a separate temperature option.
- `ANI_IDLE_COLD = 51,         // Idle Cold (plays P_BRRR.wav twice)`
- `ANI_IDLE_HOT = 52,          // Idle Hot (plays P_PANT.wav)`

**Comment by hogsy** [comment]
You're right, the original game figured out "temperature" based on the skybox name but that's not exactly modder friendly. Will sort this out later today 👍 

Day / Night could be determined by the pitch of the sun, or do you think that would be too inflexible?
