### ISSUE TITLE
Map rendering and optimization

### ISSUE THREAD

**Issue by DummkopfOfHachtenduden** [TalonBraveInfo/OpenHoW#7]
https://github.com/TalonBraveInfo/OpenHoW/blob/bc4486e4379c5b0d8edf4453f36f1c5fbe9ffffe/libpork/map.c#L182-L186

I want to use this issue to discuss and brainstorm possible map rendering and performance optimizations.

# Rendering
For our target render, we have PSX and PC version as reference. 

| PSX | PC |
| ---- | --- |
| ![original](https://user-images.githubusercontent.com/13951844/34764565-35fa8968-f5ef-11e7-966d-2051ea052967.PNG) | ![original pc](https://user-images.githubusercontent.com/13951844/34764563-35c2ca8c-f5ef-11e7-9d34-47fe39020469.png)
| ![originalunderwater](https://user-images.githubusercontent.com/13951844/34764566-3616fa4e-f5ef-11e7-97a4-b064778d2b6d.png) | ![original pcunderwater](https://user-images.githubusercontent.com/13951844/34764564-35deed2a-f5ef-11e7-86ac-e0fa70a7fd11.png)

The terrain looks mostly the same except for slight shading differences.

The water on PSX is actually part of the terrain. The terrain tiles alpha channel provides a semi transparent non-reflective surface. We are looking through the terrain onto the lower half of the Skybox/-sphere, thus archiving a "reflection". While swimming the water is blended additive on the pig, to visually indicate being underwater.

The water on PC.... I don't belive it was style choice and rather a workaround solution either due to DirectX 7 and/or hardware or other limitations. There is no "reflection" and no indication other than the swimming animation that you're actually underwater. But there is a "wave effect" with 2 sliding textures.

## Testing with Unity

**AlphaTransparent without waterplane**
![transparentalpha - nowaterplane](https://user-images.githubusercontent.com/13951844/34764560-358d01d6-f5ef-11e7-8f89-0e7b212697a7.PNG)
- Easy & fast

**AlphaCut with waterplane using a modern reflective water shader**
![transparentcutout - reflectivewaterplane](https://user-images.githubusercontent.com/13951844/34764562-35a82ccc-f5ef-11e7-9d72-889cafb611df.PNG)

# Optimization
## Mesh
|                   | Vertices | Triangles | SetPass calls |
| ------------ | -------  | --------- | ------------- |
| Brute force | 4225     | 8320      | 1             |
| Chunked (16x16)     | 6400     | 8192      | 256           |

- LOD (overkill?)

## Texturing
**2K texture per map**
- Easy
- Slow updates
- High memory footprint

vs

**128x128 texture per chunk**
- Reasonable updates time
- High memory footprint

vs

**Tile-atlas-texture per map (think .PTG)**
- Fast update time
- Low memory footprint

vs

**Splatmap**
- Fast update time
- Low memory footprint
- **Not compatible with original maps, due to tiles?**

## Culling
- Frustum culling
- Occlusion culling
- Testing against `64*64=256` chunks.
- Chunks bonding box can enclose containing objects to also cull them.

## Pathfinding
- Chunk based navigation pre-calculation before checking tiles.

## Destruction
- Quad tree?
- Tesselation?

**Comment by hogsy** [comment]
Using an implementation of the splatmap method would be nice down the line to have but I don't see this being possible anytime soon and certainly wouldn't be possible with the existing content. Once the project is a little further along (e.g. playable) I would like to work on a spec for extensions to the existing formats used in the game.

I've considered using a texture-atlas, e.g. merging all the textures together into a blob, so I'm sort of leaning towards something along these lines though people using larger custom textures is something I'm keeping in mind.

LOD for the terrain - again, I don't think this is worth doing in the short-term but possibly longer term if we were to support larger maps? Culling tiles somehow should be sufficient enough for the time being. About the only usage of LOD I'm aware of in the original game was for the pig meshes (and switching them with imposters, aka sprites, when they were far away enough).

**Comment by hogsy** [comment]
Closing this due to the amount of progress that's been made since this ticket was raised. If anything comes up we can open a more specific ticket for discussion.
