### ISSUE TITLE
Rare occassion in which some console variables aren't being registered

### ISSUE THREAD

**Issue by hogsy** [TalonBraveInfo/OpenHoW#82]
Likely an internal fault with the platform library, so may need to rectify the fault there.

I reproduced this once quite sometime ago and we had a report of it yesterday.

**Comment by hogsy** [comment]
Was probably rectified by https://github.com/TalonBraveInfo/OpenHoW/commit/e9989a40a4d9be7833350e7bf85d3a38e01d7def

Waiting for testing.

**Comment by sabas** [comment]
Now ```map camp``` works
