### ISSUE TITLE
Include git commit ID in version data and introduce 'version' command

### ISSUE THREAD

**Issue by hogsy** [TalonBraveInfo/OpenHoW#99]
Some solutions are provided [here](https://stackoverflow.com/questions/6526451/how-to-include-git-commit-number-into-a-c-executable) though they're not great.

Should ensure that this is printed to the logs as well, as this will make tracking down some faults a little easier.

**Comment by solemnwarning** [comment]
Its not perfect, but I usually put -DVERSION=xxx in the CFLAGS as necessary (see [here](https://github.com/solemnwarning/rehex/blob/38fa555619303271731fd39da08174e77eaaafc8/Makefile#L150)).

**Comment by hogsy** [comment]
Another solution is provided here though it will only work each time CMake is run.

http://xit0.org/2013/04/cmake-use-git-branch-and-commit-details-in-project/

This might not be _too_ bad, because it still means our releases will have the correct information.
